### ISSUE TITLE
Input graph format

### ISSUE THREAD

**Issue by RecoderChris** [NVSL/blaze#1]
Thanks for your efforts to open-source BLAZE. I have successfully run BFS on the graph dataset in the format of `adj+index `file you provided. However, if the raw graph dataset is in **edgelist format** (as originally provided in [SNAP](https://snap.stanford.edu/data/index.html)), is there any tool to transform the edgelist to the graph format supported in BLAZE(`adj+index`)? I find an executable file as `build/bin/convert`, which seems like as a format conversion to the `adj+index`, but I can not figure out how to run this program. 

Looking forward to your reply!

**Comment by xiaomaoaichiyu** [comment]
@RecoderChris
Hi, bro. 
I do know how to transform the edgelist to the format used by Blaze(adj + index)
First, you should use [Galois](https://github.com/IntelligentSoftwareSystems/Galois) to transform the edgelist to .gr format file, which actually is the input of Blaze converter.
Then, you can just compile and use the .gr file to generate (adj + index)

```
# in Galois, after build
./build/bin/tools/graph-convert/graph-convert --help. # use this to see the params
./build/tools/graph-convert/graph-convert --edgelist2gr [input path] [output path]
# if you need edge value, just use the --edgeType param
# Also, you can find the --gr2tgr param which can help you get the .tgr file for Blaze (adj + index)


# Then in Blaze, after build
./build/bin/convert --help # use this to see useage.
./build/bin/convert [.gr file path] [.gr.index path] [.gr.adj path]
```
If you only use one disk, then the above is enough for you. For more than one disk, I think you just need to set the -numDisks param. (But I have not try this, you need try it yourself)

Hope this help you!

**Comment by RecoderChris** [comment]
Thank you very much! I have run it successfully.
